<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ml</name>
  <version>0.0.1</version>
  <description>Stage1/2/4 ML models — slot encoder, color net, relation grounding.</description>
  <maintainer email="lsu031111@hanyang.ac.kr">su</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <test_depend>pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
